spring:
  profiles: dev
server:
  port: 7000
---
spring:
  profiles: qa
server:
  port: 7001
---
spring:
  profiles: prod
server:
  port: 7002
---
spring:
  profiles:
    active: qa
---
management:
  security:
    enabled: false
---
logging:
  level:
    org.springframework.web: ERROR
    com.aa: DEBUG
email: onlyankur@gmail.com
thread-pool: 10
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
management:
  endpoint:
    health:
      show-details: "ALWAYS"


